apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-rest
  labels:
    app: user-management-rest
    service-type: rest
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-rest
  template:
    metadata:
      labels:
        app: user-management-rest
        service-type: rest
        tier: backend
    spec:
      containers:
      - name: user-management
        image: trabalho1-user-management-rest:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: pspd-config
              key: LOG_LEVEL
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
