apiVersion: v1
kind: Service
metadata:
  name: analytics-rest
  labels:
    app: analytics-rest
    service-type: rest
spec:
  selector:
    app: analytics-rest
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
