apiVersion: v1
kind: Service
metadata:
  name: url-shortener-rest
  labels:
    app: url-shortener-rest
    service-type: rest
spec:
  selector:
    app: url-shortener-rest
  ports:
  - name: http
    protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
